### ISSUE TITLE
Extension page - disqus comments

### ISSUE THREAD

**Issue by rgrp** [ckan/extensions.ckan.org#10]
* [ ] Enable disqus comments

**Comment by jqnatividad** [comment]
@rgrp what about using something like discourse.org instead (see https://github.com/ckan/ideas-and-roadmap/issues/44)?  I realize that means spinning up another host, but it might be worthwhile to have something like talk.ckan.org, similar to what mozilla is trying to do - https://discourse.mozilla-community.org.

IMHO, it may also be a good complement to the CKAN documentation sites.

**Comment by maxious** [comment]
There's a Open Knowledge Discourse site http://discuss.okfn.org/

**Comment by rgrp** [comment]
@jqnatividad I meant disqus for each extension page only. As disqus integrates with the site naturally so I'd go for that - we're not looking to create a whole forum.
