### ISSUE TITLE
Add extension ckanext-twitterview

### ISSUE THREAD

**Issue by MrkGrgsn** [ckan/extensions.ckan.org#105]
Extension URL: https://github.com/DataShades/ckanext-twitterview
Extension Author(s): Link Digital
Compatibility: tested with CKAN 2.5
Title: A CKAN extension for previewing Twitter feed resources
Name (Unique): twitterview

**Comment by jqnatividad** [comment]
Hi @MrkGrgsn thanks for this contribution!  Should I use Link Web Services Pty Ltd or Link Digital?  Other contribs from your team use Link Web Services.

**Comment by MrkGrgsn** [comment]
Hi @jqnatividad We're shifting to using Link Digital which is our operating name. I guess we'll also update existing extensions at some point.

**Comment by jqnatividad** [comment]
OK then, I could make the changes to all the existing extensions.  Just let me know! 

I added twitterview in the meantime - http://extensions.ckan.org/extension/twitterview/

**Comment by MrkGrgsn** [comment]
Yes, if you can update the existing ones that would be great, thanks!

**Comment by jqnatividad** [comment]
Done. https://github.com/ckan/extensions.ckan.org/commit/34c016e1205496587909cb7f009b80e2f7d90d20

**Comment by MrkGrgsn** [comment]
Thanks @jqnatividad
