### ISSUE TITLE
Add Extension ckanext-dcatapit

### ISSUE THREAD

**Issue by tdipisa** [ckan/extensions.ckan.org#106]
**Extension URL:** https://github.com/geosolutions-it/ckanext-dcatapit
**Extension Author(s):** GeoSolutions (https://github.com/geosolutions-it)
**Compatibility:** CKAN 2.4 or later
**Title:** CKAN extension for the Italian Open Data Portals (DCAT_AP-IT).
**Name (Unique):** dcatapit

**Comment by tdipisa** [comment]
Hello, can we have news about this?

**Comment by jqnatividad** [comment]
Sorry @tdipisa for the delay... grazie per il tuo contributo! :)

Added it to the catalog - https://github.com/ckan/extensions.ckan.org/commit/11a64fcd4bf7137f65cd3868134c602b5837696e

**Comment by tdipisa** [comment]
Thank you so much @jqnatividad
