### ISSUE TITLE
Add CKAN widget to extension catalog

### ISSUE THREAD

**Issue by loleg** [ckan/extensions.ckan.org#107]
As per okfn/ckan.js#29 a widget is proposed for the extension catalogue.

Extension URL: https://github.com/opendata-swiss/ckan-embed
Extension Author(s): Oleg Lavrovsky (https://github.com/datalets)
Compatibility: CKAN 2.4 or later
Title: jQuery widget to embed CKAN datasets on external sites.
Name (Unique): embed

**Comment by jqnatividad** [comment]
Thanks for this valuable contribution!  Looking forward to using it!
