### ISSUE TITLE
Add extension ckanext-discovery

### ISSUE THREAD

**Issue by torfsen** [ckan/extensions.ckan.org#108]
**Extension URL:** https://github.com/stadt-karlsruhe/ckanext-discovery
**Extension Author(s):** [City of Karlsruhe, Germany](https://github.com/stadt-karlsruhe)
**Compatibility:** CKAN 2.6
**Title:** Improved searching and browsing
**Name:** discovery

**Comment by jqnatividad** [comment]
Thanks for this amazing contribution!
