### ISSUE TITLE
Add Extension s3-resources

### ISSUE THREAD

**Issue by joelchoo** [ckan/extensions.ckan.org#110]
Extension URL: https://github.com/datagovsg/ckanext-s3-resources
Extension Author(s): data.gov.sg
Compatibility: >= 2.3
Title: Upload resources to AWS S3
Name (Unique): s3-resources

**Comment by TkTech** [comment]
Always nice to see more options! Out of curiosity does this do something that ckanext-cloudstorage does not?

**Comment by joelchoo** [comment]
We've drafted a write up [here](https://medium.com/@datagovsg/ac817af9a057) that's going to be released once this gets accepted here.

Basically, we hook on to `before/after_create/update` in `IResourceController` and `IPackageController` instead of using `IUploader` because we bundle the resource files together in a zip file with a metadata file.

**Comment by TkTech** [comment]
Fantastic, love seeing these kinds of write-ups. It's definitely not something that is currently possible with ckanext-cloudstorage. How are you avoiding worker process lockup with large uploads? Are you using the background worker framework to do the actual zip file?

**Comment by joelchoo** [comment]
We're not doing that right now, but thanks for bringing that up! I'll look into it.

**Comment by joelchoo** [comment]
We're going to start work on making the uploads async using the background worker framework. I've seen the [docs here](http://docs.ckan.org/en/latest/maintaining/background-tasks.html) but was wondering if you know of any good examples of extensions that use the background worker framework that I can take a look at as I figure it out?

**Comment by TkTech** [comment]
@joelchoo unfortunately we just switched to this new system so I don't think many [any?] extensions have moved over yet. Our IRC channel or stackoverflow are both good places to get help if you run into any problems.

**Comment by joelchoo** [comment]
Ah got it, thanks! We'd love to be one of the first ones then.

**Comment by jqnatividad** [comment]
@joelchoo thanks to the data.gov.sg team for this wonderful contribution! Sorry for the delay...
