### ISSUE TITLE
Add extension ckanext-tableauview

### ISSUE THREAD

**Issue by etj** [ckan/extensions.ckan.org#113]
**Extension URL**: https://github.com/geosolutions-it/ckanext-tableauview
**Extension Author**: Emanuele Tajariol - GeoSolutions
**Compatibility**: Running on CKAN 2.6, but any CKAN >=2.3 should work
**Title**: A view plugin to display tableau public vizzes.
**Name**: tableauview

**Comment by jqnatividad** [comment]
Awesome!  This makes for cleaner tableau resource view instead of just using the webview!
