### ISSUE TITLE
Add Extension ckanext-resourceauthorizer

### ISSUE THREAD

**Issue by nmchau87** [ckan/extensions.ckan.org#114]
- Extension URL: https://github.com/etri-odp/ckanext-resourceauthorizer
- Extension Author(s): Chau Nguyen - ETRI
- Compatibility: Running on CKAN 2.7.3, but any CKAN >= 2.3 should work
- Title: Acl-based permission control at resource-level
- Name (Unique): resourceauthorizer

**Comment by jqnatividad** [comment]
Thanks for this!
