### ISSUE TITLE
Add Extension wirecloud_view

### ISSUE THREAD

**Issue by aarranz** [ckan/extensions.ckan.org#122]
- **Extension URL**: https://github.com/conwetlab/ckanext-wirecloud_view
- **Extension Author(s)**: CoNWeT Lab. Universidad Politécnica de Madrid
- **Compatibility**: Currently, the plugin supports CKAN 2.6, 2.7 and 2.8. The idea is to support, at least, the three latest sable releases.
- **Title**: CKAN extension that provides visualization and customizable dashboards for dataset resources using the FIWARE WireCloud component
- **Name (Unique)**: `wirecloud_view`

**Comment by jqnatividad** [comment]
Hi @aarranz!

The way the catalog works, it pulls the README from the master branch.  Noticed that wirecloud_view doesn't have one, that's why the generate script doesn't work.  Do you intend to have a "master" branch in that repo? 

If not, I'll just generate the entry manually.

**Comment by aarranz** [comment]
Hi @jqnatividad!

I think it is better to be compatible with your update script, so I've renamed develop to master.

Thank you very much

**Comment by jqnatividad** [comment]
Thanks for this contribution!
