### ISSUE TITLE
Add Extension baepublisher

### ISSUE THREAD

**Issue by fdelavega** [ckan/extensions.ckan.org#124]
* **Extension URL**: https://github.com/FIWARE-TMForum/ckanext-baepublisher
* **Extension Author(s)**: CoNWeT Lab. Universidad Politécnica de Madrid
* **Compatibility**: Currently, the plugin supports CKAN 2.6, 2.7 and 2.8. The idea is to support, at least, the three latest stable releases.
* **Title**: CKAN extension that provides support to create data offerings in the FIWARE Business API Ecosystem for datasets secured with the FIWARE Security Framework
* **Name (Unique)**: `baepublisher`

**Comment by jqnatividad** [comment]
Thanks for this contribution!
