### ISSUE TITLE
Add Extension ckanext-hdfs

### ISSUE THREAD

**Issue by nmchau87** [ckan/extensions.ckan.org#128]
- Extension URL: https://github.com/etri-odp/ckanext-hdfs
- Extension Author(s): Chau Nguyen - ETRI
- Compatibility: Running on CKAN 2.7.3, but any CKAN >= 2.3 should work
- Title: Big data storage with HDFS
- Name (Unique): hdfs

**Comment by jqnatividad** [comment]
Thanks @nmchau87!
