### ISSUE TITLE
Add Extension ckanext-jena

### ISSUE THREAD

**Issue by nmchau87** [ckan/extensions.ckan.org#129]
- Extension URL: https://github.com/etri-odp/ckanext-jena
- Extension Author(s): Chau Nguyen - ETRI
- Compatibility: Running on CKAN 2.7.3, but any CKAN >= 2.3 should work
- Title: Semantic data management with Apache Jena
- Name (Unique): jena

**Comment by jqnatividad** [comment]
Thanks again @nmchau87!
