### ISSUE TITLE
Add Extension ckanext-keycloak

### ISSUE THREAD

**Issue by nmchau87** [ckan/extensions.ckan.org#130]
- Extension URL: https://github.com/etri-odp/ckanext-keycloak
- Extension Author(s): Chau Nguyen - ETRI
- Compatibility: Running on CKAN 2.7.3, but any CKAN >= 2.3 should work
- Title: SSO Authentication with Keycloak
- Name (Unique): keycloak

**Comment by jqnatividad** [comment]
Thanks @nmchau87 for this valuable contribution!

**Comment by sntgmrtnz** [comment]
Is this extension still working? I am not having any success with it. Any help would be much appreciated.
