### ISSUE TITLE
Add Extension OAuth2

### ISSUE THREAD

**Issue by aitormagan** [ckan/extensions.ckan.org#17]
Extension URL: https://github.com/conwetlab/ckanext-oauth2
Extension Author(s): CoNWeT
Compatibility: 2.2
Title: CKAN OAuth2
Name (Unique): ckanext-oauth2conwet

We were not able to work with the extension provided by EtaLab (ckanext-oauht2). For this reason, we have improved their extension and create a new one that is working on some sites (FIWARE Lab: https://data.lab.fi-ware.org).

**Comment by jqnatividad** [comment]
Done.
