### ISSUE TITLE
Add Extension Private Datasets

### ISSUE THREAD

**Issue by aitormagan** [ckan/extensions.ckan.org#19]
Extension URL: https://github.com/conwetlab/ckanext-privatedatasets
Extension Author(s): CoNWeT
Compatibility: 2.2
Title: CKAN PrivateDatasets
Name (Unique): ckanext-privatedatasets

This extension allow users to manage the visibility of a dataset, even if the dataset does not belong to an organization.

**Comment by jqnatividad** [comment]
Thanks so much for your submission! Checking the conwetlab GH repos, we hope to see more in the future!

**Comment by aitormagan** [comment]
We are working on it! ;)
