### ISSUE TITLE
Including Natural History Museum Extensions

### ISSUE THREAD

**Issue by rgrp** [ckan/extensions.ckan.org#24]
Check which NHM extensions are not yet included and include them: https://github.com/NaturalHistoryMuseum

Has some very cool mapping: http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb?view_id=f4301659-ef2a-4239-a0d5-cce3c46f7a30&q=mollusca&filters=

**Comment by jqnatividad** [comment]
Hi @rgrp, took an initial stab at it in master list.  And yeah, https://github.com/NaturalHistoryMuseum/ckanext-map is really cool!

Perhaps, @aliceh75 et al. can help finalize?

**Comment by aliceh75** [comment]
Hi, here is the list of re-usable extensions we have:

- **ckanext-ldap** provides ldap authentication. It is quite feature full, and I'm confident it is stable. It does lack a proper test suite, so maybe it could be included as an alpha.

    https://github.com/NaturalHistoryMuseum/ckanext-ldap

- **ckanext-userdatasets** allows per-user datasets (so individual users can only edit/delete their own datasets but not other people's in the same organization). Having implemented this, it is clear that it was not something CKAN was supposed to do in the first place - so while I'm confident it is safe now, there is always a risk that future CKAN code will make this unsafe. It has a full test suite.

     https://github.com/NaturalHistoryMuseum/ckanext-userdatasets

- **ckanext-tiledmap** creates a new map view which uses a custom map tile renderer to display large number of points on a map. It also provides polygon search which can be applied to any view. Ideally it should be split into two components: ckanext-datastore-spatial to generate spatial fields on datastore and provide the polygon search, and ckanext-tilemap to provide the mapping. But it is fine as it is! It will not work with ckan 2.2 though, only (the yet to be released) 2.3

    The ckan extention is at https://github.com/NaturalHistoryMuseum/ckanext-map and the tile server (nodejs, build on top of CartoDB's windshaft) at https://github.com/NaturalHistoryMuseum/nhm-windshaft-app

- **ckanpackager** is a separate service that can accept requests to fetch a resource from a ckan server, zip it up and email a link to a given address. ckanpackager will apply filters to datastore resources, so allows users to download parts of resource only. 

    ckanpackager can be found at https://github.com/NaturalHistoryMuseum/ckanpackager , and there is a ckan extension that will replace the download button with one that invokes the ckanpackager service: https://github.com/NaturalHistoryMuseum/ckanext-ckanpackager

- **ckanext-contact** adds a contact form. In use. @benscott will know more.

    https://github.com/NaturalHistoryMuseum/ckanext-contact

- **ckanext-feedback** adds a feedback form. In use. @benscott will know more.

    https://github.com/NaturalHistoryMuseum/ckanext-feedback

- **ckanext-graph** adds a graph view which allows aggregate values. In use. @benscott will know more.

    https://github.com/NaturalHistoryMuseum/ckanext-graph

- **ckanext-gallery** adds a dataset gallery view. In use. @benscott will know more.

    https://github.com/NaturalHistoryMuseum/ckanext-gallery

- **ckanext-doi** adds Digital Ojbect Identifiers (DOI) to datasets. In use. @benscott will know more.

    https://github.com/NaturalHistoryMuseum/ckanext-doi

- ckanext-cacheapi and ckanext-dev are currently not in use and not developed.

**Comment by jqnatividad** [comment]
@aliceh75 this is amazing stuff!  Have updated the [master list](https://docs.google.com/spreadsheets/d/1izCpljO6Et7zLUKcUlB4BzsMZTurENp56Iqi9kXOtgs/edit#gid=0), and will push it out once @benscott checks off on the master list info.
