### ISSUE TITLE
Update Extensions in Kata team repositories

### ISSUE THREAD

**Issue by razz0** [ckan/extensions.ckan.org#29]
We have updated README files of a few of the Kata team repositories. Please update the descriptions of the following extensions to the extension list.

https://github.com/kata-csc/ckanext-ddi
https://github.com/kata-csc/ckanext-oaipmh
https://github.com/kata-csc/ckanext-rems
https://github.com/kata-csc/ckanext-shibboleth

Please also remove (or hide) **https://github.com/kata-csc/ckanext-urn** from the list as it is not really useful and is not under development any more.

**Comment by jqnatividad** [comment]
Got it.  Will update after International Open Data Day/Code Across.
