### ISSUE TITLE
Add Extension ckanext-ytp-comments

### ISSUE THREAD

**Issue by Zharktas** [ckan/extensions.ckan.org#49]
Extension URL: https://github.com/yhteentoimivuuspalvelut/ckanext-ytp-comments
Extension Author(s): Valtori Government ICT Centre
Compatibility: 2.2 - 2.3
Title: CKAN Comments for Datasets
Name (Unique): ckanext-ytp-comments

**Comment by jqnatividad** [comment]
Added. Thanks!!!
