### ISSUE TITLE
Add Extension ckanext-ytp-request

### ISSUE THREAD

**Issue by Zharktas** [ckan/extensions.ckan.org#50]
Extension URL: https://github.com/yhteentoimivuuspalvelut/ckanext-ytp-request
Extension Author(s): Valtori Government ICT Centre
Compatibility: 2.2 - 2.3
Title: CKAN Request for membership
Name (Unique): ckanext-ytp-request

**Comment by jqnatividad** [comment]
Added.  Thanks for your contribution!
