### ISSUE TITLE
Add Extension wpcomments

### ISSUE THREAD

**Issue by jmikkonen** [ckan/extensions.ckan.org#62]
Extension URL: https://github.com/Helsingin-kaupungin-tietokeskus/ckanext-comments
Extension author: Helsinki Region Infoshare
Compatibility: CKAN 2.x, WordPress 3.9+
Title: WordPress Comments for CKAN Datasets
Name (Unique): wpcomments
- Janne Mikkonen, HiQ Finland on behalf of HRI

**Comment by jqnatividad** [comment]
Thanks for your contribution!
