### ISSUE TITLE
Add Extension multiedit

### ISSUE THREAD

**Issue by jmikkonen** [ckan/extensions.ckan.org#63]
Extension URL: https://github.com/Helsingin-kaupungin-tietokeskus/ckanext-multiedit
Extension author: Helsinki Region Infoshare
Compatibility: CKAN 2.x
Title: Multiedit
Name (Unique): multiedit
- Janne Mikkonen, HiQ Finland on behalf of HRI

**Comment by jqnatividad** [comment]
Thanks heaps for your contribution!  Open Data with Open Source is the way to go! :)
