### ISSUE TITLE
Add Extension ckanext-dataproxy

### ISSUE THREAD

**Issue by ozooner** [ckan/extensions.ckan.org#70]
Hi,

Apologies for confusing name, as there exists something similar to proxy resources via ckan. This extension however enables previewing data in foreign databases using recline.js as frontend. It will enable users creating a new resource to enter connection string and table name, and rest will be taken care by the extension.

URL: https://github.com/cphsolutionslab/ckanext-dataproxy
Name: ckanext-dataproxy (or ckanext-databaseproxy)
Author(s): cphsolutionslab, fadeit ApS (http://fadeit.dk)
Compatibility: 2.2.1 & 2.3 (v2.3 branch)
Title: An extension that allows previewing remote database tables in CKAN recline view (MySQL, PostgreSQLl, MSSQL)

**Comment by jqnatividad** [comment]
Thanks for the contribution!  Keep em coming!
