### ISSUE TITLE
Add extension ckanext-customuserprivileges

### ISSUE THREAD

**Issue by ozooner** [ckan/extensions.ckan.org#71]
URL: https://github.com/cphsolutionslab/ckanext-customuserprivileges
Name: ckanext-customuserprivileges
Author(s): cphsolutionslab, fadeit ApS (http://fadeit.dk)
Compatibility: 2.4 (likely compatible with older versions as-well)
Title: Fine-tune who can edit dataset whether it's unowned or organization owned

**Comment by jqnatividad** [comment]
Done!  Thanks for contributing back and sharing this extension with the CKAN community!
