### ISSUE TITLE
ckan-comments

### ISSUE THREAD

**Issue by palcu** [ckan/extensions.ckan.org#72]
[This extension](http://extensions.ckan.org/extension/comments/) is not available.

**Comment by jqnatividad** [comment]
Thanks for the heads-up!  @rossjones, is it hosted elsewhere or should we remove it from the catalog.

**Comment by rossjones** [comment]
No, it was entirely a work-in-progress and never meant to be used.  It really shouldn't have been listed.

Should use http://extensions.ckan.org/extension/ytp-comments/ for this I think
