### ISSUE TITLE
Add Extension DDI Importer

### ISSUE THREAD

**Issue by metaodi** [ckan/extensions.ckan.org#73]
**Extension URL:** https://github.com/liip/ckanext-ddi
**Extension Author(s):** Liip, World Bank
**Compatibility:** CKAN 2.3+
**Title:** DDI Importer/Harvester
**Name (Unique):** ddi-importer

**Comment by jqnatividad** [comment]
Thanks for your contribution!  BTW, http://data.worldbank.org/ doesn't look like a CKAN instance.  Is this used in another publicly accessible CKAN instance?

**Comment by metaodi** [comment]
@jqnatividad as far as I know there is currently no productive CKAN instance using this extension. We have a test instance, if you're interested: http://ckan-ddi.clients.liip.ch
