### ISSUE TITLE
Add Extension Tagmanager

### ISSUE THREAD

**Issue by alantygel** [ckan/extensions.ckan.org#75]
Extension URL: https://github.com/alantygel/ckanext-tagmanager
Extension Author(s): Alan Tygel
Compatibility: 2.5
Title: Tagmanager
Name (Unique): ckanext-tagmanager

**Comment by jqnatividad** [comment]
This is awesome and thanks for your contribution!  

Hopefully, some integration between http://extensions.ckan.org/extension/climate-tagger/ and this extension can be done in the future to automatically tag documents (mainly PDFs), and then manage the resulting tags with this.

**Comment by alantygel** [comment]
great, looking forward to this!

On Fri, Nov 20, 2015 at 6:00 PM, Joel Natividad notifications@github.com
wrote:

> This is awesome and thanks for your contribution!
> 
> Hopefully, some integration between
> http://extensions.ckan.org/extension/climate-tagger/ and this extension
> can be done in the future to automatically tag documents (mainly PDFs), and
> then manage the resulting tags with this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ckan/extensions.ckan.org/issues/75#issuecomment-158460075
> .

## 

Programa de Pós-Graduação em Informática - PPGI/UFRJ
EITA - Educação, Informação e Tecnologias para Autogestão
Núcleo de Solidariedade Técnica - Soltec/UFRJ http://www.soltec.ufrj.br
http://www.cirandas.net/alantygel
http://www.contraosagrotoxicos.org
