### ISSUE TITLE
Add extension (FIWARE) Store Publisher 

### ISSUE THREAD

**Issue by aitormagan** [ckan/extensions.ckan.org#80]
Extension URL: https://github.com/conwetlab/ckanext-storepublisher
Extension Author(s): CoNWeT
Compatibility: 2.2
Title: CKAN Store Publisher
Name (Unique): ckanext-storepublisher

CKAN extension to publish public datasets in the FIWARE Store as offerings

**Comment by jqnatividad** [comment]
Another great extension from CoNWeT Lab.  Thanks again for sharing this with the community.
