### ISSUE TITLE
Add extension NGSI View

### ISSUE THREAD

**Issue by amercader** [ckan/extensions.ckan.org#86]
- Extension URL: https://github.com/telefonicaid/ckanext-ngsiview
- Extension Author(s): Guillermo Zarzuelo
- Compatibility: CKAN >= 2.2
- Title: Allows to create and visualize NGSI resources provided by a Context broker
- Name (Unique): ngsiview

**Comment by amercader** [comment]
Cheers @jqnatividad

**Comment by jqnatividad** [comment]
Though the README.md needs to be updated to allow the scnshots to display
https://github.com/telefonicaid/ckanext-ngsiview/pull/13

cc @gzarrub
