### ISSUE TITLE
Add Extension googleauth

### ISSUE THREAD

**Issue by andreafeccomandi** [ckan/extensions.ckan.org#87]
**Extension URL**: https://github.com/yacme/ckanext-googleauth
**Extension Author**: Yacme S.r.l (dev@yacme.com)
**Compatibility**: CKAN 2.5.1 and CKAN 2.4.1
**Title**: CKAN extension for use Google as authentication authority
**Name**: googleauth

**Comment by jqnatividad** [comment]
Done!  Thanks @andreafeccomandi for this valuable contribution!

BTW, have you checked out Auth0's Auth-as-a-Service offering?  We're thinking of integrating it with CKAN.
