### ISSUE TITLE
New extension "Dgvat XLS-Export"

### ISSUE THREAD

**Issue by datagvat** [ckan/extensions.ckan.org#89]
For the CKAN instance used for the Austrian open data catalogue https://www.data.gv.at a custom extension was created which allows group-admin to export datasets from their organizations to export all datasets to a .xls worksheet. Sysadmins may choose to export datasets from any organization they want or to export all datasets of all groups. 

The according source code is available at https://github.com/datagvat/ckanext-dgvat_xls

**Comment by jqnatividad** [comment]
Thanks for this valuable contribution!
