### ISSUE TITLE
Add Extension CKAN TextCaptcha

### ISSUE THREAD

**Issue by MrkGrgsn** [ckan/extensions.ckan.org#90]
Extension URL: https://github.com/DataShades/ckanext-textcaptcha
Extension Author(s): Link Web Services
Compatibility: 2.3, 2.4 Not tested in 2.5
Title: Text captcha for user registration
Name (Unique): textcaptcha

**Comment by jqnatividad** [comment]
Thanks for this valuable contribution!  Will be sure to tweet about it tomorrow AM EST and share this extension with the CKAN community!

**Comment by MrkGrgsn** [comment]
Thanks @jqnatividad!
