### ISSUE TITLE
Add extension Screendoor

### ISSUE THREAD

**Issue by ajb** [ckan/extensions.ckan.org#91]
Extension URL: https://github.com/dobtco/screendoor-ckan
Extension Author(s): The Department of Better Technology
Compatibility: >= 2.0 
Title: CKAN Sync for Screendoor
Name (Unique): screendoor-ckan

**Comment by jqnatividad** [comment]
Thanks for this awesome contribution!  Let's keep making awesome govtech! ;)

**Comment by ajb** [comment]
❤️
