### ISSUE TITLE
Add Extension ckanext-aaf

### ISSUE THREAD

**Issue by Psykar** [ckan/extensions.ckan.org#92]
Thanks :)

Extension URL: https://github.com/Psykar/ckanext-aaf
Extension Author(s): Louis des Landes (Swinburne University)
Compatibility: 2.5.1+
Title: Allows AAF (Australian Acceess Federation) authentication to log into a CKAN installation.
Name (Unique): aaf

**Comment by jqnatividad** [comment]
Thanks for this!  The AAF Rapid Connect approach is very interesting and should be a model followed in other opendata, govtech agile integration deployments.  Is there more info about it beyond what's on https://rapid.aaf.edu.au/?  

Will tweet about ckanext-aaf tomorrow AM EST.  Would be nice if I can point to an overview about AAF Rapid Connect as well...

**Comment by Psykar** [comment]
An overview from a development point of view is here:
https://rapid.aaf.edu.au/developers

I don't think there's much else about rapid connect itself, although a bit about AAF is here:
https://aaf.edu.au/about/

**Comment by Psykar** [comment]
(I should mention I'm not associated with AAF at all)
