### ISSUE TITLE
Update ckanext-issues

### ISSUE THREAD

**Issue by davidread** [ckan/extensions.ckan.org#93]
See: https://github.com/ckan/ckanext-issues/issues/60

**Comment by jqnatividad** [comment]
Hi @davidread, is there a publicly available site where we can see the latest ckanext-issues in action?

**Comment by davidread** [comment]
We have it running on data.gov.uk for one publisher so far - HSCIC: https://data.gov.uk/issues

Screenshots including what admins see are here: http://guidance.data.gov.uk/issues_management.html

We have some (mainly visual) customizations though, in ckanext-dgu.

I don't know of it running anywhere else, aside from when you used it a while ago

**Comment by jqnatividad** [comment]
Thanks for the info!  Looking to make issues a standard install on our implementations...  One comment I get is that if Issues can have some kind of per post visibility setting - i.e. org admins/editors can see all issues, but not all members/public - to supplement internal workflow, etc.  

Anyways, this is not the place to discuss this...  will create an issue on ckanext-issue once a client actually requires it... :)

**Comment by davidread** [comment]
I'm keen to resist private issues tbh. Of course public bodies hate being open if they can, given the choice. But we need to push the principle of openness here, and it helps issues get resolved quickly if the body knows it is being watched how well and quickly it answers the issue.
