### ISSUE TITLE
Add extension ckanext-extractor

### ISSUE THREAD

**Issue by torfsen** [ckan/extensions.ckan.org#96]
_Extension URL:_ https://github.com/stadt-karlsruhe/ckanext-extractor
_Extension Author:_ City of Karlsruhe, Germany
_Compatibility:_ Developed and tested with CKAN 2.5, other versions may or may not work
_Title:_ Full text and metadata extractor
_Name:_ extractor

**Comment by davidread** [comment]
Great! Is it running somewhere? Are you going to tweet about it too?

**Comment by torfsen** [comment]
We're running it in our own instance, which is scheduled to go public later this month. It's been working well and we currently haven't any plans for major changes so it seemed like a good moment to publish it. Feel free to spread the word.

**Comment by jqnatividad** [comment]
Nice!!!  Added it to the catalog.  Once you go public with the portal, please let us know so we can tweet and point folks to it!

**Comment by jqnatividad** [comment]
@torfsen is the portal publicly available yet?

**Comment by torfsen** [comment]
@jqnatividad No, but we're planning to launch this month. I will report back.

**Comment by torfsen** [comment]
We're now online: https://transparenz.karlsruhe.de (German only)

**Comment by davidread** [comment]
Great to see the launch. However this feature doesn't work for me for some reason. I searched for "Weststadt": https://transparenz.karlsruhe.de/dataset?q=weststadt&-res_format=PDF&sort=title_string+asc
which I'd have thought would bring up this CSV:
https://transparenz.karlsruhe.de/dataset/altersstruktur/resource/afacccdb-9e98-4b78-997c-98c2864fb294
Have I misunderstood

**Comment by torfsen** [comment]
@davidread Extraction is only activated for some file formats, in our case only for PDFs. For example, if you [search for "Heimatstadt"](https://transparenz.karlsruhe.de/dataset?q=heimatstadt) ("home town") then you'll find [this document](https://transparenz.karlsruhe.de/dataset/daten-und-fakten/resource/312cc182-3c69-4727-b8da-15b8545fc366), although the term "Heimatstadt" only occurs in the full text of the PDF.

It is possible to also search in CSVs (as in any other file format that is supported by Solr), see the option [`ckanext.extractor.indexed_formats`](https://github.com/stadt-karlsruhe/ckanext-extractor#formats-for-extraction). In our case there is little benefit so we're not doing it, but if your CSVs contain interesting textual data then this might be an option.

**Comment by davidread** [comment]
Ah, thanks for explaining! Sounds great :)
