### ISSUE TITLE
Add Extension datasetthumbnail

### ISSUE THREAD

**Issue by martinburchell** [ckan/extensions.ckan.org#97]
URL: https://github.com/aptivate/ckanext-datasetthumbnail
Author: Aptivate
Compatibility: 2.5.2
Title: Generation and display of thumbnail images for datasets

**Comment by jqnatividad** [comment]
Thanks for this contribution!  Do you have a publicly available site we can see it in action?

**Comment by martinburchell** [comment]
All of the plugins Aptivate have developed recently will appear in the new catalogue for MapAction http://mapaction.org but the catalogue hasn't been made public yet.
